before_script:
  - 'if [ "$RAVEN_VERSION" ]; then npm install raven-js@$RAVEN_VERSION; fi'
env:
  - RAVEN_VERSION="latest"
  - RAVEN_VERSION="^3.0.0"
  - RAVEN_VERSION="~3.9.0"
language: node_js
node_js:
  - "node"
after_success:
  - bash <(curl -s https://codecov.io/bash)
